### ISSUE TITLE
Themes no longer working?

### ISSUE THREAD

**Issue by PsyintZ** [0mniscient/Discord-Themes#38]
Whenever I try to load one of your themes (specifically Quiet), it is unsuccessful. It returns an error messaging about not being able to "load the META." 

Is this going to be fixed, or is there a way I can fix it myself? Or should I start looking for another theme? If there is any way to fix it, I would certainly prefer to do that because I absolutely love your themes! They are leagues above all of the other ones I've tried. :1st_place_medal: 

Thanks in advance, and keep up the great work @0mniscient ! 👍

**Comment by 0mniscient** [comment]
Pretty weird that this happens what you can do is make a new file in your themes folder called Quiet.theme.css and just open that with a notepad and just manually copy and paste everything from here https://raw.githubusercontent.com/0mniscient/Discord-Themes/master/Themes/Quiet.theme.css into the file itself. If it still occurs then idk what's the problem because it's a very rare case when it happens
